# Generated by Django 4.1 on 2022-12-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_customuser_password_alter_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Password',
            field=models.CharField(default=1234, max_length=50, verbose_name='Пароль:'),
        ),
    ]
