# Generated by Django 4.1 on 2022-12-15 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Password',
        ),
    ]
