# Generated by Django 4.1 on 2022-12-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=50, verbose_name='Пароль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='post',
            field=models.CharField(choices=[('Пользователь', 'Пользователь'), ('Менеджер', 'Менеджер'), ('Админ', 'Админ')], default='Пользователь', max_length=50, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин'),
        ),
    ]
