# Generated by Django 4.1 on 2022-12-15 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_customuser_password_alter_customuser_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=0, max_length=50, verbose_name='Пароль'),
        ),
    ]
