# Generated by Django 4.1 on 2022-12-15 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_customuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=False, max_length=50, verbose_name='Пароль'),
        ),
    ]
